/**
 * Production config entrypoint.
 * `medusa start` will use this compiled JS when ts-node is not available.
 * Generated by `medusa build` into .medusa/server/medusa-config.js
 * This file delegates to the compiled build output.
 */
// eslint-disable-next-line @typescript-eslint/no-var-requires
module.exports = require('./.medusa/server/medusa-config');
